# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsmsausage < Formula
  desc "Example binary distribution using goreleaser and homebrew"
  homepage "https://github.com/VargasRaymondJ/homebrew-jackalope-test"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/VargasRaymondJ/awsmsauce/releases/download/v0.10.0/awsmsauce_0.10.0_Darwin_arm64.tar.gz"
      sha256 "7344c25cb50422f098b5eca7afcf915b6ac7fd48587ee94dcff95970d0b2bab9"

      def install
        bin.install "awsmsausage"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/VargasRaymondJ/awsmsauce/releases/download/v0.10.0/awsmsauce_0.10.0_Darwin_x86_64.tar.gz"
      sha256 "197fb062f1fc49f73202b08ba5fd5f4e622dbd24136f3509e62ddd78c5edba62"

      def install
        bin.install "awsmsausage"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/VargasRaymondJ/awsmsauce/releases/download/v0.10.0/awsmsauce_0.10.0_Linux_arm64.tar.gz"
      sha256 "6701c84bcdef2605f8ff7bd89d9151b0fb23dd12bbd79032360626ef14d4529f"

      def install
        bin.install "awsmsausage"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/VargasRaymondJ/awsmsauce/releases/download/v0.10.0/awsmsauce_0.10.0_Linux_x86_64.tar.gz"
      sha256 "3980bbba22fe3f7614ef53cf12eab39be63a98c3817b1b3475185005a2b8fcfe"

      def install
        bin.install "awsmsausage"
      end
    end
  end
end
